name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cffrestre/diplomado-ci-cd:${{ github.sha }}
      
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Push Docker image
      with:
        image: cffrestre/diplomado-ci-cd
        tags: ${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: cffrestre
        password: ${{ secrets.DOCKESECRET }}
